(* MS-DOS path grammar in ebnf notation *)
path = drive? {dir} file
dir = <sep> | subdir
drive = drive-letter <drive-sep>
drive-letter = #'[a-zA-Z]'
file = file-name {'.' ext}
subdir = #'[^\\:]+'
file-name = #'[^\\.:]+'
ext = #'[^\\.:]+'
drive-sep = ':'
sep = <'\\'>
